config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :highways do
    resources :comments
  end
  resources :routes

  resources :accidents
  resources :home
  resources :region
  resources :ranking
  
  resources :highways do
    collection { post :import}
  end

  resources :accidents do
    collection { post :import }
  end

   post '/routes/trace' => 'routes#trace_route', as: :trace_route
   get '/highways/1/ranking' => 'highways#ranking_1', as: :ranking_1
   get '/highways/2/ranking' => 'highways#ranking_2', as: :ranking_2

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-tabs nav-justified" role="tablist">

  <%= render 'layouts/navigation_links' %>

</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'Home', root_path %></li>
<li><%= link_to 'Ranking', highway_path(1) %></li>
<li><%= link_to 'Rodovia', highways_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Set the default page title as "Pé na estrada" -->
    <title><%= content_for?(:title) ? yield(:title) : "Pé na estrada" %></title>

    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pé na estrada" %>">

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXiD6hoj8mw6Hd-DrNKZc7dNn3Agu9wxY&v=3.exp&libraries=visualization"></script>
    <script src='https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/src/markerclusterer.js'></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body background="/assets/fundo.jpg">
    <div class="panel-heading">
      <header class="navbar navbar-fixed-top">
        <div class="navbar navbar-default ">

          <div class="navbar-header">
            <div id="logo">
              <a href="<%=root_path%>">
                <%= image_tag("logo.jpg", height: '100%', width: '100%', alt:"Pé na estada")%>
              </a>
            </div>
          </div>

          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">

              <li class="link"><%= link_to 'Traçar Rota', routes_path, class: "navbar-brand" %></li>
              <li class="link"><%= link_to 'Ranking', ranking_1_path, class: "navbar-brand" %></li>
              <li class="link "><%= link_to 'Rodovia', highways_path, class: "navbar-brand" %></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
              <li id="about" class="link "><%= link_to 'Sobre', home_path(1), class: "navbar-brand" %></li>
            </ul>
          </div>

        </div>
      </header>
    </div>

    <div id="main_panel" class="panel panel-default container" style="width: 90%;  border: 1px solid #d4d4d4;">
      <div class="panel-body">
        <div id = "content" >
          <main role="main">

            <%= render 'layouts/messages' %>
            <%= yield %>

          </main>
        </div>
      </div>
      <!--   <div class="panel-footer">Panel footer</div> -->
    </div>
  </body>
</html>